// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/payments": {
            "post": {
                "description": "Validates a payment and, if valid, forwards it to the acquiring bank for authorization.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Process a payment",
                "parameters": [
                    {
                        "description": "Payment to process",
                        "name": "payment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PostPaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Authorized or Declined",
                        "schema": {
                            "$ref": "#/definitions/models.PaymentResponse"
                        }
                    },
                    "400": {
                        "description": "Rejected: invalid request",
                        "schema": {
                            "$ref": "#/definitions/models.PostPaymentErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Payment could not be processed",
                        "schema": {
                            "$ref": "#/definitions/models.PostPaymentErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/payments/{id}": {
            "get": {
                "description": "Returns a previously processed payment by its id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Retrieve a payment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Payment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.PaymentResponse"
                        }
                    },
                    "404": {
                        "description": "Payment not found"
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.pong"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.pong": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "models.PaymentResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "Amount in the minor currency unit, e.g. 1050 = £10.50.",
                    "type": "integer"
                },
                "card_number_last_four": {
                    "description": "CardNumberLastFour is the last four digits of the card used.",
                    "type": "integer"
                },
                "currency": {
                    "description": "Currency is the ISO currency code of the payment.",
                    "type": "string"
                },
                "expiry_month": {
                    "description": "ExpiryMonth of the card, 1–12.",
                    "type": "integer"
                },
                "expiry_year": {
                    "description": "ExpiryYear of the card.",
                    "type": "integer"
                },
                "id": {
                    "description": "Id is the gateway-assigned payment id (a GUID), used to retrieve the payment.",
                    "type": "string"
                },
                "payment_status": {
                    "description": "PaymentStatus is the outcome of a created payment: Authorized or Declined.",
                    "type": "string",
                    "enum": [
                        "Authorized",
                        "Declined"
                    ]
                }
            }
        },
        "models.PostPaymentErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "Error is a human-readable description of why the request could not be processed.",
                    "type": "string"
                },
                "payment_status": {
                    "description": "PaymentStatus is always \"Rejected\" for an error response.",
                    "type": "string",
                    "enum": [
                        "Rejected"
                    ]
                }
            }
        },
        "models.PostPaymentRequest": {
            "type": "object",
            "required": [
                "amount",
                "card_number",
                "currency",
                "cvv",
                "expiry_month",
                "expiry_year"
            ],
            "properties": {
                "amount": {
                    "description": "Amount in the minor currency unit, e.g. 1050 = £10.50.",
                    "type": "integer",
                    "example": 1050
                },
                "card_number": {
                    "description": "Card number: 14–19 characters, digits only.",
                    "type": "string",
                    "example": "2222405343248877"
                },
                "currency": {
                    "description": "ISO currency code; must be one of USD, GBP, EUR.",
                    "type": "string",
                    "example": "GBP"
                },
                "cvv": {
                    "description": "Card verification value: 3–4 characters, digits only.",
                    "type": "string",
                    "example": "123"
                },
                "expiry_month": {
                    "description": "Expiry month, 1–12. The month/year combination must be in the future.",
                    "type": "integer",
                    "example": 4
                },
                "expiry_year": {
                    "description": "Expiry year. The month/year combination must be in the future.",
                    "type": "integer",
                    "example": 2030
                }
            }
        }
    },
    "tags": [
        {
            "description": "Process and retrieve card payments",
            "name": "payments"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8090",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Payment Gateway API",
	Description:      "Processes card payments through an acquiring bank and retrieves previously made payments.\nA payment ends in one of three states: Authorized, Declined, or Rejected (failed validation, never sent to the bank).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
